gen:
	@prisma generate --schema=C:\_dev\Projects\FossHack\scriblio\prisma\schema.prisma

start:
	@npm run start

studio:
	@prisma generate --schema=C:\_dev\Projects\FossHack\scriblio\prisma\schema.prisma
